image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

include:
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

variables:
  SECURE_LOG_LEVEL: info
  DS_JAVA_VERSION: 11
  DOCKER_DRIVER: overlay
  CONTAINER_IMAGE: smartcommunitylab/playngo-ext-visits:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  CONTAINER_IMAGE_LATEST: smartcommunitylab/playngo-ext-visits:$CI_COMMIT_REF_NAME-latest
  SAST_JAVA_VERSION: 11
  CS_IMAGE: smartcommunitylab/playngo-ext-visits:$CI_COMMIT_REF_NAME-latest

update-backend-cache-image:
  stage: build
  variables:
    BUILDKIT_PROGRESS: plain
    DOCKER_BUILDKIT: 1 
  script:
    - docker login -u $DHUB_USER -p $DHUB_PASS
    - docker build -f Dockerfile-cache -t $CONTAINER_CACHE_IMAGE .
    - docker push $CONTAINER_CACHE_IMAGE
  rules:
    - changes:
      - backend/pom.xml

backend-container-build:
  stage: build
  environment:
    name: $CI_COMMIT_REF_NAME
  script:
    - docker login -u $DHUB_USER -p $DHUB_PASS
    - DOCKER_BUILDKIT=1 docker build -t $CONTAINER_IMAGE -t $CONTAINER_IMAGE_LATEST .
    - docker push $CONTAINER_IMAGE
    - docker push $CONTAINER_IMAGE_LATEST
  only:
    - dev
    - prod
    - main

spotbugs-sast:
  rules:
     - if: '$CI_COMMIT_REF_NAME == "main"'

semgrep-sast:
  rules:
     - if: '$CI_COMMIT_REF_NAME == "main"'

nodejs-scan-sast:
  rules:
     - if: '$CI_COMMIT_REF_NAME == "main"'

gemnasium-maven-dependency_scanning:
  rules:
     - if: '$CI_COMMIT_REF_NAME == "main"'

gemnasium-dependency_scanning:
  rules:
     - if: '$CI_COMMIT_REF_NAME == "main"'

container_scanning:
  stage: test
  variables:
    DOCKER_IMAGE: smartcommunitylab/playngo-ext-visits:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    DOCKERFILE_PATH: "Dockerfile"
    GIT_STRATEGY: fetch
    DOCKER_USER: ""
    DOCKER_PASSWORD: ""
  dependencies:
    - backend-container-build
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

deploy-dev:
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: ['']
  environment:
    name: dslab
  script:
    - echo "deploy playngo-ext-visits"
    - kubectl -n playngo-dev set image deployments/playngo-ext-visits playngo-ext-visits=$CONTAINER_IMAGE --record=true
    - kubectl -n playngo-dev rollout status deployment playngo-ext-visits
  only:
    - dev
    - prod

deploy-prod:
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: ['']
  environment:
    name: dslab
  script:
    - echo "deploy playngo-ext-visits"
    - kubectl -n playngo-prod set image deployments/playngo-ext-visits playngo-ext-visits=$CONTAINER_IMAGE --record=true
    - kubectl -n playngo-prod rollout status deployment playngo-ext-visits
  only:
    - dev
    - prod