image: docker:19

services:
  - docker:dind

stages:
  - test
  - build
  - container-build
  - container-scan
  - deploy-dev
  - deploy-prod

variables:
  SECURE_LOG_LEVEL: info
  DS_JAVA_VERSION: 11
  DOCKER_DRIVER: overlay
  CONTAINER_IMAGE: smartcommunitylab/playngo-ext-visits:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  CONTAINER_IMAGE_LATEST: smartcommunitylab/playngo-ext-visits:$CI_COMMIT_REF_NAME-latest
  SAST_JAVA_VERSION: 11

maven-build:
  image: maven:3-openjdk-11
  stage: build
  script:
    - mvn -DskipTests=true clean package

backend-container-build:
  stage: container-build
  environment:
    name: $CI_COMMIT_REF_NAME
  script:
    - docker login -u $DHUB_USER -p $DHUB_PASS
    - DOCKER_BUILDKIT=1 docker build -t $CONTAINER_IMAGE -t $CONTAINER_IMAGE_LATEST .
    - docker push $CONTAINER_IMAGE
    - docker push $CONTAINER_IMAGE_LATEST
  only:
    - dev
    - prod

include:
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

container_scanning:
  stage: container-scan
  variables:
    DOCKER_IMAGE: smartcommunitylab/playngo-ext-visits:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    DOCKERFILE_PATH: "Dockerfile"
    GIT_STRATEGY: fetch
    DOCKER_USER: ""
    DOCKER_PASSWORD: ""

deploy-dev:
  stage: deploy-dev
  image: 
    name: bitnami/kubectl:latest
    entrypoint: ['']
  environment:
    name: platform-new
  script:
    - echo "deploy playngo-ext-visits"
    - kubectl -n playngo-dev set image deployments/playngo-ext-visits playngo-ext-visits=$CONTAINER_IMAGE --record=true
    - kubectl -n playngo-dev rollout status deployment playngo-ext-visits
  only:
    - dev
    - prod

deploy-prod:
  stage: deploy-prod
  image: 
    name: bitnami/kubectl:latest
    entrypoint: ['']
  environment:
    name: platform-new
  script:
    - echo "deploy playngo-ext-visits"
    - kubectl -n playngo-prod set image deployments/playngo-ext-visits playngo-ext-visits=$CONTAINER_IMAGE --record=true
    - kubectl -n playngo-prod rollout status deployment playngo-ext-visits
  only:
    - dev
    - prod