image: docker:19

services:
  - docker:dind

stages:
  - test
  - build
  - container-build
  - container-scan
  - deploy

variables:
  SECURE_LOG_LEVEL: info
  DS_JAVA_VERSION: 11
  DOCKER_DRIVER: overlay
  CONTAINER_IMAGE: smartcommunitylab/playngo-visits-ext:v2-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  CONTAINER_IMAGE_LATEST: smartcommunitylab/playngo-visits-ext:v2-$CI_COMMIT_REF_NAME-latest
  SAST_JAVA_VERSION: 11

maven-build:
  image: maven:3-openjdk-11
  stage: build
  script:
    - mvn -DskipTests=true clean package

backend-container-build:
  stage: container-build
  environment:
    name: $CI_COMMIT_REF_NAME
  script:
    - docker login -u $DHUB_USER -p $DHUB_PASS
    - DOCKER_BUILDKIT=1 docker build -f src/main/docker/Dockerfile.jvm --build-arg VER=1.0 -t $CONTAINER_IMAGE -t $CONTAINER_IMAGE_LATEST .
    - docker push $CONTAINER_IMAGE
    - docker push $CONTAINER_IMAGE_LATEST
  only:
    - dev

include:
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

container_scanning:
  stage: container-scan
  variables:
    DOCKER_IMAGE: smartcommunitylab/playngo-visits-ext:v2-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    DOCKERFILE_PATH: "src/main/docker/Dockerfile.jvm"
    GIT_STRATEGY: fetch
    DOCKER_USER: ""
    DOCKER_PASSWORD: ""

deploy:
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: ['']
  environment:
    name: platform-new
  script:
    - echo "deploy playngo-visits-ext"
    - kubectl -n playngo-dev set image deployments/playngo-visits-ext playngo-visits-ext=$CONTAINER_IMAGE --record=true
    - kubectl -n playngo-dev rollout status deployment playngo-visits-ext
  only:
    - dev
